### ISSUE TITLE
pip install -r requirements.txt Fails

### ISSUE THREAD

**Issue by kashanico** [Azure-Samples/python-docs-hello-world#42] opened 2020-08-18 22:52 UTC
When I try to do the pop install I get this error

ImportError: cannot import name 'Feature' from 'setuptools' (c:\users\kkashani\python-docs-hello-world\env\lib\site-packages\setuptools\__init__.py)

**Comment by JoaquinHoffmann** [comment] 2020-09-08 22:00
> 
> 
> pip install feature
> Or
> pip3 install feature

I had the same issue, but this didn't work, however I uninstalled setuptools (had version 47) and then installed version 45.0.0 because the problem is for versions higher than 46

**Comment by kraigb** [comment] 2020-09-23 17:07
@kashanico Can you git pull the sample and try again? We had an old version of MarkupSafe in requirements.txt, which I've cleaned up to reference only Flask, which should pull in the correct versions of its own dependencies and fix this error.

**Comment by tonybaloney** [comment] 2021-03-18 21:28
Confirmed that this fixed the issue after testing locally. I'm closing this for now, but if you have any other problems, please raise another issue.

**Closed by tonybaloney** 2021-03-18 21:28 UTC
